# -*- coding: utf-8 -*-
"""001_El_problema.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHw22wzw4nWcSGE283yMhpyHYSaolkBd

## Parte 1: El Problema - El Texto es solo una "Sopa de Letras" para la Computadora
"""

#texto = "La CEO de ACME, Lisa Chang, viajará a México para supervisar los nuevos proyectos de energía renovable. Ella se mostró muy entusiasmada."
texto = """
La inteligencia artificial transforma radicalmente la manera en que las organizaciones analizan información.
Algoritmos complejos permiten automatizar procesos de recopilación, limpieza y visualización de datos heterogéneos.
El aprendizaje automático, una subdisciplina fundamental, utiliza modelos estadísticos para identificar patrones,
predecir comportamientos y optimizar decisiones estratégicas con eficiencia y precisión.
"""
print(texto)

"""¿Cómo contamos las palabras acá?
len(texto) nos da los caracteres, no sirve. Podríamos usar texto.split(). Hagamos la prueba.
"""

palabras = texto.split()# Usar texto.split() divide el texto por espacios, pero no elimina puntuación ni entiende contexto.
# Este enfoque básico no nos permite analizar con precisión nombres, verbos o entidades.
print(palabras)

#🧠 ¿Qué hace esto?
#Divide el texto por espacios. Es una tokenización básica, sin comprender contexto.

#🧱 Limitaciones:
#"ACME," y "Chang," quedan con coma incluida → errores al comparar.
#Verbos conjugados, artículos, puntuación... todo se trata como si fueran iguales.
#Python no entiende roles gramaticales ni entidades.

"""Limitaciones (El "Porqué" necesitamos algo mejor):

- "ACME," y "Chang," tienen la coma pegada. No son palabras "limpias".
- "La" y "los" son artículos. viajará es una forma conjugada del verbo "viajar". ¿Cómo reducimos todo a su forma base para poder analizar frecuencias o temas?
- ¿Cómo sabe la máquina que "ACME" es una organización y "Lisa Chang" es una persona? Para Python, ahora mismo, son solo cadenas de texto idénticas a "proyectos".

## Parte 2: La Solución - spaCy, el Intérprete Lingüístico
"""

!pip install spacy -q
!python -m spacy download es_core_news_sm -q

import spacy
# spacy transforma el texto en un objeto "Doc", que contiene tokens, lemas, entidades, roles gramaticales y más.
# Este procesamiento permite trabajar con el texto de forma estructurada y lingüísticamente informada.

# Cargar el modelo de español
nlp = spacy.load("es_core_news_sm")#carga el modelo en español preentrenado.

# Procesar nuestro texto
doc = nlp(texto)#convierte el texto en un objeto Doc que spaCy puede analizar (tokenizar, etiquetar, lematizar, etc.)

print(doc)

"""## Parte 3: Desglosando el Objeto Doc - Los Fundamentos de NLP en Acción

**Tokenización (La Unidad Mínima)**

Definición: Un token es la unidad mínima de texto con significado (una palabra, un número, un signo de puntuación).
"""

for token in doc:
    print(token.text)

#¿Qué es un token? Es la unidad mínima significativa del texto: puede ser una palabra, número o puntuación.
# Cada token representa una palabra o signo de puntuación.
# spaCy hace una tokenización inteligente, separando puntuación de las palabras.

"""**Lematización (La Raíz de la Palabra)**

Definición: El "lema" es la forma canónica o de diccionario de una palabra. Es la clave para agrupar palabras con el mismo significado.
"""

print("PALABRA\t\tLEMA")
print("-------\t\t----")
for token in doc:
    # Imprimimos el texto del token y su lema
    print(f"{token.text:<15}\t{token.lemma_}")

# Lematización: reduce una palabra a su forma base.
# Permite agrupar diferentes formas verbales o plurales para análisis más uniforme.
#¿Qué es un lema? Es la forma base o de diccionario de una palabra. Ej: "viajará" → "viajar"
#Muy útil para agrupar formas distintas de una palabra bajo el mismo concepto.

"""**Part-of-Speech (POS) Tagging (El Rol Gramatical)**

Definición: Etiquetar cada palabra según su función gramatical (Sustantivo, Verbo, Adjetivo, etc.).
"""

print("PALABRA\t\tPOS\t\tEXPLICACIÓN")
print("-------\t\t---\t\t-----------")
for token in doc:
    print(f"{token.text:<15}\t{token.pos_:<10}\t{spacy.explain(token.pos_)}")

#🧠 ¿Qué es POS (Part-of-Speech)? El rol gramatical de una palabra en una oración: sustantivo, verbo, adjetivo, etc.
# POS tagging: asigna una categoría gramatical a cada palabra.
# Esto ayuda a entender la estructura sintáctica del texto.
# Ejemplo: distinguir entre "correr" como verbo o como sustantivo.