# -*- coding: utf-8 -*-
"""000_LangExtract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDNAy5OHwL8k1W5z1N9PMpICJ2P3dsOX

# Introducción a la Extracción de Información con LangExtract

¡Bienvenidos a la primera clase de Procesamiento del Lenguaje Natural (PLN)!

En este cuaderno, exploraremos una herramienta muy útil para la extracción de información de texto: **LangExtract**. Esta librería, desarrollada por Google, aprovecha el poder de los modelos de lenguaje grandes como Gemini para identificar y extraer entidades y relaciones específicas de un texto de forma estructurada.

Es importante destacar que LangExtract es una *herramienta* que facilita el proceso de extracción, pero no es una solución mágica. La calidad de la extracción depende en gran medida de la definición clara de la tarea, el diseño del prompt y la provisión de ejemplos de alta calidad.

Este cuaderno servirá como una demostración práctica de cómo utilizar LangExtract para una tarea de extracción simple, mostrándoles el flujo de trabajo desde la instalación hasta la visualización de los resultados.

Para más detalles sobre LangExtract, pueden consultar la siguiente referencia:
[Introducing LangExtract: A Gemini-powered information extraction library](https://developers.googleblog.com/es/introducing-langextract-a-gemini-powered-information-extraction-library/)
"""

!pip install -U langextract -q
## Instalamos la librería LangExtract para tareas de extracción de información usando modelos de lenguaje como Gemini.
#Es una herramienta de alto nivel para extraer entidades y relaciones a partir de texto usando LLMs.

# Importamos librerías necesarias para la extracción de texto y para acceder a las claves API desde Google Colab.
import textwrap #formatear correctamente strings multilínea (como el prompt), eliminando sangrías innecesarias.
import langextract as lx # es la librería de Google usada para realizar extracciones de información desde texto usando modelos LLM como Gemini.
import os# os se usa para acceder al sistema de archivos y manejar variables de entorno como la clave API de LangExtract.
from google.colab import userdata # userdata permite acceder de forma segura a claves guardadas como secretos en Google Colab, como la API key de Gemini.

# Intentamos recuperar la clave API de Gemini almacenada como secreto en Colab.
# Si se encuentra, se asigna como variable de entorno para que LangExtract pueda autenticar los requests.

secret_names = ['GEMINI_API_KEY', 'GOOGLE_API_KEY']
api_key_found = False

for sn in secret_names:
    try:
        # Intenta obtener la clave con uno de los nombres posibles
        api_key = userdata.get(sn)

        # Si se encuentra, la asignamos a la variable de entorno que langextract espera
        os.environ['LANGEXTRACT_API_KEY'] = api_key
        print(f"✅ Clave de API cargada exitosamente desde: '{sn}'")
        api_key_found = True
        break # Salimos del bucle una vez que encontramos la clave
    except userdata.SecretNotFoundError:
        # Si no se encuentra, simplemente continúa al siguiente nombre
        continue
    except Exception as e:
        print(f"❗️ Ocurrió un error inesperado: {e}")
        break

if not api_key_found:
    print("\n❌ ERROR: No se pudo encontrar una clave de API.")
    print(f"Asegúrate de haber guardado tu clave en los secretos de Colab con uno de estos nombres: {secret_names}")
    print("Andá al panel izquierdo -> 🔑 Secretos -> Nuevo secreto.")

# 1. Definimos el prompt (instrucción) para el modelo. Aquí especificamos qué tipo de información queremos extraer del texto.
#🧠 ¿Por qué es importante el prompt?
#LangExtract usa prompts como los LLM tradicionales. La claridad y precisión del prompt influye directamente en la calidad de las extracciones.

prompt = textwrap.dedent("""\
    Extrae personajes, emociones y relaciones en orden de aparición.
    Usa el texto exacto para las extracciones. No parafrasees ni superpongas entidades.
    Proporciona atributos significativos para cada entidad para añadir contexto.""")

# 2. Proporcionar un ejemplo de alta calidad para guiar al modelo.
# Creamos un ejemplo de entrenamiento para guiar al modelo.
# Especificamos manualmente qué entidades y relaciones debe detectar, junto con atributos contextuales.
examples = [
    lx.data.ExampleData(
        text="ROMEO. ¡Pero, silencio! ¿Qué luz alumbra esa ventana? Es el oriente, y Julieta es el sol.",
        extractions=[
            lx.data.Extraction(
                extraction_class="personaje",
                extraction_text="ROMEO",
                attributes={"estado_emocional": "asombro"}
            ),
            lx.data.Extraction(
                extraction_class="emocion",
                extraction_text="¡Pero, silencio!",
                attributes={"sentimiento": "admiración suave"}
            ),
            lx.data.Extraction(
                extraction_class="relacion",
                extraction_text="Julieta es el sol",
                attributes={"tipo": "metáfora"}
            ),
        ]
    )
]

print("Definición de la tarea de extracción creada.")

# El texto de entrada a procesar.
# Texto de entrada sobre el cual se aplicará la extracción automática.
#input_text = "Si me quieres, quiéreme entera, no por zonas de luz o sombra… Si me quieres, quiéreme negra y blanca, Y gris, verde, y rubia, y morena… Quiéreme día, quiéreme noche… ¡Y madrugada en la ventana abierta!… Si me quieres, no me recortes: ¡Quiéreme toda!… O no me quieras"

input_text = "Lady Julieta contemplaba con anhelo las estrellas, su corazón dolía por Romeo"

# Ejecutar la extracción.
# Nota: Esto hará una llamada a la API de Gemini, lo cual puede incurrir en costos.
# Ejecutamos la extracción de información utilizando el modelo "gemini-1.5-flash".
# Esta operación envía el texto y el prompt a la API y devuelve una estructura con las entidades encontradas.

result = lx.extract(
    text_or_documents=input_text,
    prompt_description=prompt,
    examples=examples,
    model_id="gemini-1.5-flash", # Modelo rápido y eficiente.
)
# Ejecutamos la extracción de información utilizando el modelo "gemini-1.5-flash".
# Esta operación envía el texto y el prompt a la API y devuelve una estructura con las entidades encontradas.


# Imprimir las extracciones para ver el resultado estructurado.
print("Texto de Entrada:")
print(f'"{result.text}"\n')
print("Extracciones Encontradas:")
# Iteramos sobre las extracciones devueltas por el modelo y mostramos:
# - Clase de entidad (personaje, emoción, relación)
# - Texto exacto extraído
# - Atributos adicionales y posición en el texto
#🧠 Esto es muy útil si querés usar estos datos luego para entrenamiento de modelos supervisados o para análisis lingüístico.
for entity in result.extractions:
    print(f"- Clase: {entity.extraction_class}")
    print(f"  Texto: {entity.extraction_text}")
    if entity.attributes:
        print(f"  Atributos: {entity.attributes}")
    if entity.char_interval:
        print(f"  Posición: ({entity.char_interval.start_pos}-{entity.char_interval.end_pos})\n")

# Guardamos las extracciones en un archivo JSONL y generamos una visualización interactiva en HTML.
# Esto permite explorar gráficamente las entidades extraídas sobre el texto.

from IPython.display import display, HTML

# Guardar los resultados en un archivo JSONL en memoria (opcional, pero es un buen hábito/buena practica).
# Para la visualización, necesitamos guardar y luego cargar el archivo.
output_dir = "/content/langextract_output"
os.makedirs(output_dir, exist_ok=True)
lx.io.save_annotated_documents([result], output_name="extraction_results.jsonl", output_dir=output_dir)

# Generar el contenido HTML desde el archivo de resultados.
html_content = lx.visualize(f"{output_dir}/extraction_results.jsonl")

# Mostrar la visualización interactiva en la celda de Colab.
display(html_content)

"""¡Espero que este cuaderno te haya sido útil para iniciarte en la extracción de información con LangExtract y que te motive a explorar más a fondo las capacidades de Google Colab!

Con Colab, podes aprovechar al máximo el potencial de este entorno para tus proyectos de PLN y mucho más.

Para seguir aprendiendo sobre Google Colab y sus funcionalidades, te recomiendo visitar:
[https://medium.com/google-colab](https://medium.com/google-colab)
"""

from IPython.display import YouTubeVideo

video_id = "8VFYs3Ot_aA"
YouTubeVideo(video_id, width=800, height=450)