# -*- coding: utf-8 -*-
"""001_Gradio_BeautifulS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCBMaml8AbT7qlVVaN0B7qBP37dcE5Z1
"""

# ================================
# 🔹 INSTALACIÓN E IMPORTACIÓN
# ================================

# Instalamos Gradio si no está presente
!pip install gradio -q

# Importamos Gradio para crear interfaces web simples
import gradio as gr

# Importamos BeautifulSoup para parsear HTML (procesamiento de texto web)
from bs4 import BeautifulSoup

# ================================
# 🟩 EJEMPLO 1: Saludo simple con texto
# ================================

# Función básica que saluda al usuario
def bienvenida(name):
    return "Hola " + name

# Creamos una interfaz con un cuadro de texto como entrada y salida de texto
bienvenido = gr.Interface(fn=bienvenida, inputs="text", outputs="text")

# Lanzamos la interfaz web
bienvenido.launch()

# ================================
# 🟩 EJEMPLO 2: Saludo con intensidad usando slider
# ================================

# Saludo que repite el mensaje dependiendo del valor del slider
def saludo(nombre, intensidad):
    return "Hola, " + nombre + "!" * int(intensidad)

# Interfaz con dos entradas: texto y slider, y una salida de texto
demo = gr.Interface(
    fn=saludo,
    inputs=["text", "slider"],
    outputs="text",
)

demo.launch()

# ================================
# 🟩 EJEMPLO 3: Textbox personalizado con etiquetas
# ================================

# Función simple de saludo en inglés
def greet(name):
    return "Hello " + name

# Componente Textbox personalizado
textbox = gr.Textbox(
    label="Type your name here:",
    placeholder="John Doe",
    lines=2
)

# Interfaz con un textbox más configurable
gr.Interface(fn=greet, inputs=textbox, outputs="text").launch()

# ================================
# 🌐 USO DE BEAUTIFULSOUP
# ================================

# HTML de ejemplo
html = """
<html>
<head>
  <title>Mi Página de Ejemplo</title>
</head>
<body>
  <h1>Título Principal</h1>
  <p>Este es un párrafo.</p>
  <a href="https://www.ejemplo.com">Enlace a Ejemplo</a>
</body>
</html>
"""

# Creamos el objeto BeautifulSoup para parsear el HTML
soup = BeautifulSoup(html, 'html.parser')

# Imprimimos todo el objeto parseado
print(soup)

# ================================
# 📌 Acceder a etiquetas específicas
# ================================

titulo = soup.title
print(titulo)       # <title>Mi Página de Ejemplo</title>
print(titulo.text)  # Mi Página de Ejemplo

parrafo = soup.p
print(parrafo)      # <p>Este es un párrafo.</p>
print(parrafo.text) # Este es un párrafo.

# ================================
# 📌 Usar prettify() para visualizar bien el HTML
# ================================

html = """
<html><head><title>Mi Página de Ejemplo</title></head><body><h1>Título Principal</h1><p>Este es un párrafo.</p><a href="https://www.ejemplo.com">Enlace a Ejemplo</a></body></html>
"""
soup = BeautifulSoup(html, 'html.parser')
print(soup.prettify())  # Formato indentado

# ================================
# 📌 Acceder a atributos de etiquetas
# ================================

html = """
<a href="https://www.ejemplo.com" class="enlace-principal">Enlace a Ejemplo</a>
"""

soup = BeautifulSoup(html, 'html.parser')

enlace = soup.a
print(enlace['href'])   # Extrae URL
print(enlace['class'])  # Extrae clase CSS